# Generated by Django 4.0 on 2022-01-04 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_favourite_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='productId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product'),
        ),
    ]
