# Generated by Django 4.0 on 2021-12-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_rename_product_slider_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product', unique=True),
        ),
    ]
