# Generated by Django 4.0 on 2021-12-27 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_favourite_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product', unique=True),
        ),
    ]
